use crate::dom::node::NodeId;
use crate::js_runtime::state::DomState;
use deno_core::op2;
use deno_core::OpState;
use serde::Serialize;

#[derive(Serialize)]
pub struct DOMRectJson {
    pub x: f64,
    pub y: f64,
    pub width: f64,
    pub height: f64,
    pub top: f64,
    pub right: f64,
    pub bottom: f64,
    pub left: f64,
}

/// The DOM state with its sheets brought up to date, so the layout
/// applies the rules a DOM change added or removed.
fn styled_state(state: &mut OpState) -> &mut DomState {
    let state = state.borrow_mut::<DomState>();
    state.refresh_styles();
    state
}

/// Get bounding rect using real taffy layout computation.
#[op2]
#[serde]
pub fn op_layout_get_bounding_rect(state: &mut OpState, #[smi] node_id: i32) -> DOMRectJson {
    let state = styled_state(state);
    let nid = NodeId::from_raw(node_id as u32);
    let rect = state.layout_engine.get_bounding_rect(&state.dom, nid);
    DOMRectJson {
        x: rect.x,
        y: rect.y,
        width: rect.width,
        height: rect.height,
        top: rect.y,
        right: rect.x + rect.width,
        bottom: rect.y + rect.height,
        left: rect.x,
    }
}

#[op2(fast)]
#[smi]
pub fn op_layout_get_offset_width(state: &mut OpState, #[smi] node_id: i32) -> i32 {
    let state = styled_state(state);
    let nid = NodeId::from_raw(node_id as u32);
    state
        .layout_engine
        .get_offset_width(&state.dom, nid)
        .round() as i32
}

#[op2(fast)]
#[smi]
pub fn op_layout_get_offset_height(state: &mut OpState, #[smi] node_id: i32) -> i32 {
    let state = styled_state(state);
    let nid = NodeId::from_raw(node_id as u32);
    state
        .layout_engine
        .get_offset_height(&state.dom, nid)
        .round() as i32
}

#[op2(fast)]
#[smi]
pub fn op_layout_get_offset_top(state: &mut OpState, #[smi] node_id: i32) -> i32 {
    let state = styled_state(state);
    let nid = NodeId::from_raw(node_id as u32);
    state.layout_engine.get_offset_top(&state.dom, nid).round() as i32
}

#[op2(fast)]
#[smi]
pub fn op_layout_get_offset_left(state: &mut OpState, #[smi] node_id: i32) -> i32 {
    let state = styled_state(state);
    let nid = NodeId::from_raw(node_id as u32);
    state.layout_engine.get_offset_left(&state.dom, nid).round() as i32
}

/// Get computed style — reads from inline style attribute first, falls back to defaults.
/// This op needs DomState but lives here for historical reasons.
/// It's actually registered in dom_ext now — see op_dom_get_computed_style.
/// Kept as fallback for the JS bridge that still calls this name.
#[op2]
#[string]
pub fn op_get_computed_style(#[smi] _node_id: i32, #[string] property: &str) -> String {
    css_default(property)
}

pub fn css_default(property: &str) -> String {
    match property {
        "display" => "block".into(),
        "visibility" => "visible".into(),
        "opacity" => "1".into(),
        "position" => "static".into(),
        "overflow" => "visible".into(),
        "width" | "height" => "auto".into(),
        "color" => "rgb(0, 0, 0)".into(),
        "background-color" => "rgba(0, 0, 0, 0)".into(),
        "font-size" => "16px".into(),
        "font-family" => "Times".into(),
        "font-kerning" => "auto".into(),
        "font-optical-sizing" => "auto".into(),
        "font-stretch" => "100%".into(),
        "font-variant-caps" => "normal".into(),
        "font-variant-ligatures" => "normal".into(),
        "text-rendering" => "auto".into(),
        "-webkit-font-smoothing" => "auto".into(),
        "line-height" => "normal".into(),
        "margin" | "margin-top" | "margin-right" | "margin-bottom" | "margin-left" => "0px".into(),
        "padding" | "padding-top" | "padding-right" | "padding-bottom" | "padding-left" => {
            "0px".into()
        }
        "border-width" => "0px".into(),
        "box-sizing" => "content-box".into(),
        "text-align" => "start".into(),
        "letter-spacing" => "normal".into(),
        "word-spacing" => "0px".into(),
        "word-break" => "normal".into(),
        "text-indent" => "0px".into(),
        "white-space" => "normal".into(),
        "text-transform" => "none".into(),
        "text-shadow" => "none".into(),
        "direction" => "ltr".into(),
        "vertical-align" => "baseline".into(),
        "filter" => "none".into(),
        "content" => "normal".into(),
        "backdrop-filter" => "none".into(),
        "-webkit-text-fill-color" => "rgba(0, 0, 0, 0)".into(),
        "-webkit-text-stroke-color" => "rgba(0, 0, 0, 0)".into(),
        "float" => "none".into(),
        "clear" => "none".into(),
        "z-index" => "auto".into(),
        "transform" => "none".into(),
        "cursor" => "auto".into(),
        "pointer-events" => "auto".into(),
        "-webkit-border-horizontal-spacing" => "0px".into(),
        "-webkit-border-image" => "none".into(),
        "-webkit-border-vertical-spacing" => "0px".into(),
        "-webkit-box-align" => "stretch".into(),
        "-webkit-box-decoration-break" => "slice".into(),
        "-webkit-box-direction" => "normal".into(),
        "-webkit-box-flex" => "0".into(),
        "-webkit-box-ordinal-group" => "1".into(),
        "-webkit-box-orient" => "horizontal".into(),
        "-webkit-box-pack" => "start".into(),
        "-webkit-box-reflect" => "none".into(),
        "-webkit-line-break" => "auto".into(),
        "-webkit-line-clamp" => "none".into(),
        "-webkit-locale" => "auto".into(),
        "-webkit-mask-box-image" => "none".into(),
        "-webkit-mask-box-image-outset" => "0".into(),
        "-webkit-mask-box-image-repeat" => "stretch".into(),
        "-webkit-mask-box-image-slice" => "0 fill".into(),
        "-webkit-mask-box-image-source" => "none".into(),
        "-webkit-mask-box-image-width" => "auto".into(),
        "-webkit-mask-position-x" => "0%".into(),
        "-webkit-mask-position-y" => "0%".into(),
        "-webkit-rtl-ordering" => "logical".into(),
        "-webkit-ruby-position" => "before".into(),
        "-webkit-tap-highlight-color" => "rgba(0, 0, 0, 0.18)".into(),
        "-webkit-text-combine" => "none".into(),
        "-webkit-text-decorations-in-effect" => "none".into(),
        "-webkit-text-orientation" => "vertical-right".into(),
        "-webkit-text-security" => "none".into(),
        "-webkit-text-stroke-width" => "0px".into(),
        "-webkit-user-drag" => "auto".into(),
        "-webkit-user-modify" => "read-only".into(),
        "-webkit-writing-mode" => "horizontal-tb".into(),
        "accent-color" => "auto".into(),
        "align-content" => "normal".into(),
        "align-items" => "normal".into(),
        "align-self" => "auto".into(),
        "alignment-baseline" => "auto".into(),
        "anchor-name" => "none".into(),
        "anchor-scope" => "none".into(),
        "animation-composition" => "replace".into(),
        "animation-delay" => "0s".into(),
        "animation-direction" => "normal".into(),
        "animation-duration" => "0s".into(),
        "animation-fill-mode" => "none".into(),
        "animation-iteration-count" => "1".into(),
        "animation-name" => "none".into(),
        "animation-play-state" => "running".into(),
        "animation-range-end" => "normal".into(),
        "animation-range-start" => "normal".into(),
        "animation-timeline" => "auto".into(),
        "animation-timing-function" => "ease".into(),
        "animation-trigger" => "none".into(),
        "app-region" => "none".into(),
        "appearance" => "none".into(),
        "aspect-ratio" => "auto".into(),
        "backface-visibility" => "visible".into(),
        "background-attachment" => "scroll".into(),
        "background-blend-mode" => "normal".into(),
        "background-clip" => "border-box".into(),
        "background-image" => "none".into(),
        "background-origin" => "padding-box".into(),
        "background-position" => "0% 0%".into(),
        "background-repeat" => "repeat".into(),
        "background-size" => "auto".into(),
        "baseline-shift" => "0px".into(),
        "baseline-source" => "auto".into(),
        "block-size" => "80px".into(),
        "border-block-end-color" => "rgb(238, 238, 238)".into(),
        "border-block-end-style" => "solid".into(),
        "border-block-end-width" => "1px".into(),
        "border-block-start-color" => "rgb(238, 238, 238)".into(),
        "border-block-start-style" => "solid".into(),
        "border-block-start-width" => "1px".into(),
        "border-bottom-left-radius" => "0px".into(),
        "border-bottom-right-radius" => "0px".into(),
        "border-bottom-style" => "solid".into(),
        "border-bottom-width" => "1px".into(),
        "border-collapse" => "separate".into(),
        "border-end-end-radius" => "0px".into(),
        "border-end-start-radius" => "0px".into(),
        "border-image-outset" => "0".into(),
        "border-image-repeat" => "stretch".into(),
        "border-image-slice" => "100%".into(),
        "border-image-source" => "none".into(),
        "border-image-width" => "1".into(),
        "border-inline-end-color" => "rgb(238, 238, 238)".into(),
        "border-inline-end-style" => "solid".into(),
        "border-inline-end-width" => "1px".into(),
        "border-inline-start-color" => "rgb(238, 238, 238)".into(),
        "border-inline-start-style" => "solid".into(),
        "border-inline-start-width" => "1px".into(),
        "border-left-style" => "solid".into(),
        "border-left-width" => "1px".into(),
        "border-right-style" => "solid".into(),
        "border-right-width" => "1px".into(),
        "border-shape" => "none".into(),
        "border-start-end-radius" => "0px".into(),
        "border-start-start-radius" => "0px".into(),
        "border-top-left-radius" => "0px".into(),
        "border-top-right-radius" => "0px".into(),
        "border-top-style" => "solid".into(),
        "border-top-width" => "1px".into(),
        "bottom" => "auto".into(),
        "box-decoration-break" => "slice".into(),
        "box-shadow" => "none".into(),
        "break-after" => "auto".into(),
        "break-before" => "auto".into(),
        "break-inside" => "auto".into(),
        "buffered-rendering" => "auto".into(),
        "caption-side" => "top".into(),
        "caret-animation" => "auto".into(),
        "caret-color" => "rgb(51, 51, 51)".into(),
        "caret-shape" => "auto".into(),
        "clip" => "auto".into(),
        "clip-path" => "none".into(),
        "clip-rule" => "nonzero".into(),
        "color-interpolation" => "srgb".into(),
        "color-interpolation-filters" => "linearrgb".into(),
        "color-rendering" => "auto".into(),
        "color-scheme" => "normal".into(),
        "column-count" => "auto".into(),
        "column-fill" => "balance".into(),
        "column-gap" => "normal".into(),
        "column-height" => "auto".into(),
        "column-rule-break" => "normal".into(),
        "column-rule-color" => "rgb(51, 51, 51)".into(),
        "column-rule-inset-cap-end" => "0px".into(),
        "column-rule-inset-cap-start" => "0px".into(),
        "column-rule-inset-junction-end" => "0px".into(),
        "column-rule-inset-junction-start" => "0px".into(),
        "column-rule-style" => "none".into(),
        "column-rule-visibility-items" => "normal".into(),
        "column-rule-width" => "3px".into(),
        "column-span" => "none".into(),
        "column-width" => "auto".into(),
        "column-wrap" => "auto".into(),
        "contain" => "none".into(),
        "contain-intrinsic-block-size" => "none".into(),
        "contain-intrinsic-height" => "none".into(),
        "contain-intrinsic-inline-size" => "none".into(),
        "contain-intrinsic-size" => "none".into(),
        "contain-intrinsic-width" => "none".into(),
        "container-name" => "none".into(),
        "container-type" => "normal".into(),
        "content-visibility" => "visible".into(),
        "corner-bottom-left-shape" => "superellipse(1)".into(),
        "corner-bottom-right-shape" => "superellipse(1)".into(),
        "corner-end-end-shape" => "superellipse(1)".into(),
        "corner-end-start-shape" => "superellipse(1)".into(),
        "corner-start-end-shape" => "superellipse(1)".into(),
        "corner-start-start-shape" => "superellipse(1)".into(),
        "corner-top-left-shape" => "superellipse(1)".into(),
        "corner-top-right-shape" => "superellipse(1)".into(),
        "counter-increment" => "none".into(),
        "counter-reset" => "none".into(),
        "counter-set" => "none".into(),
        "cx" => "0px".into(),
        "cy" => "0px".into(),
        "d" => "none".into(),
        "dominant-baseline" => "auto".into(),
        "dynamic-range-limit" => "no-limit".into(),
        "empty-cells" => "show".into(),
        "field-sizing" => "fixed".into(),
        "fill" => "rgb(0, 0, 0)".into(),
        "fill-opacity" => "1".into(),
        "fill-rule" => "nonzero".into(),
        "flex-basis" => "auto".into(),
        "flex-direction" => "row".into(),
        "flex-grow" => "0".into(),
        "flex-line-count" => "1".into(),
        "flex-shrink" => "1".into(),
        "flex-wrap" => "nowrap".into(),
        "flood-color" => "rgb(0, 0, 0)".into(),
        "flood-opacity" => "1".into(),
        "font-feature-settings" => "normal".into(),
        "font-language-override" => "normal".into(),
        "font-palette" => "normal".into(),
        "font-size-adjust" => "none".into(),
        "font-style" => "normal".into(),
        "font-synthesis-small-caps" => "auto".into(),
        "font-synthesis-style" => "auto".into(),
        "font-synthesis-weight" => "auto".into(),
        "font-variant" => "normal".into(),
        "font-variant-alternates" => "normal".into(),
        "font-variant-east-asian" => "normal".into(),
        "font-variant-emoji" => "normal".into(),
        "font-variant-numeric" => "normal".into(),
        "font-variant-position" => "normal".into(),
        "font-variation-settings" => "normal".into(),
        "font-weight" => "400".into(),
        "forced-color-adjust" => "auto".into(),
        "grid-auto-columns" => "auto".into(),
        "grid-auto-flow" => "row".into(),
        "grid-auto-rows" => "auto".into(),
        "grid-column-end" => "auto".into(),
        "grid-column-start" => "auto".into(),
        "grid-row-end" => "auto".into(),
        "grid-row-start" => "auto".into(),
        "grid-template-areas" => "none".into(),
        "grid-template-columns" => "none".into(),
        "grid-template-rows" => "none".into(),
        "hyphenate-character" => "auto".into(),
        "hyphenate-limit-chars" => "auto".into(),
        "hyphens" => "manual".into(),
        "image-orientation" => "from-image".into(),
        "image-rendering" => "auto".into(),
        "initial-letter" => "normal".into(),
        "inline-size" => "200px".into(),
        "inset-block-end" => "auto".into(),
        "inset-block-start" => "auto".into(),
        "inset-inline-end" => "auto".into(),
        "inset-inline-start" => "auto".into(),
        "interactivity" => "auto".into(),
        "interest-delay-end" => "normal".into(),
        "interest-delay-start" => "normal".into(),
        "interpolate-size" => "numeric-only".into(),
        "isolation" => "auto".into(),
        "justify-content" => "normal".into(),
        "justify-items" => "normal".into(),
        "justify-self" => "auto".into(),
        "left" => "auto".into(),
        "lighting-color" => "rgb(255, 255, 255)".into(),
        "line-break" => "auto".into(),
        "list-style-image" => "none".into(),
        "list-style-position" => "outside".into(),
        "list-style-type" => "disc".into(),
        "margin-block-end" => "4px".into(),
        "margin-block-start" => "4px".into(),
        "margin-inline-end" => "4px".into(),
        "margin-inline-start" => "4px".into(),
        "marker-end" => "none".into(),
        "marker-mid" => "none".into(),
        "marker-start" => "none".into(),
        "mask-clip" => "border-box".into(),
        "mask-composite" => "add".into(),
        "mask-image" => "none".into(),
        "mask-mode" => "match-source".into(),
        "mask-origin" => "border-box".into(),
        "mask-position" => "0% 0%".into(),
        "mask-repeat" => "repeat".into(),
        "mask-size" => "auto".into(),
        "mask-type" => "luminance".into(),
        "math-depth" => "0".into(),
        "math-shift" => "normal".into(),
        "math-style" => "normal".into(),
        "max-block-size" => "none".into(),
        "max-height" => "none".into(),
        "max-inline-size" => "none".into(),
        "max-width" => "none".into(),
        "min-block-size" => "0px".into(),
        "min-height" => "0px".into(),
        "min-inline-size" => "0px".into(),
        "min-width" => "0px".into(),
        "mix-blend-mode" => "normal".into(),
        "object-fit" => "fill".into(),
        "object-position" => "50% 50%".into(),
        "object-view-box" => "none".into(),
        "offset-anchor" => "auto".into(),
        "offset-distance" => "0px".into(),
        "offset-path" => "none".into(),
        "offset-position" => "normal".into(),
        "offset-rotate" => "auto 0deg".into(),
        "order" => "0".into(),
        "orphans" => "2".into(),
        "outline-color" => "rgb(51, 51, 51)".into(),
        "outline-offset" => "0px".into(),
        "outline-style" => "none".into(),
        "outline-width" => "3px".into(),
        "overflow-anchor" => "auto".into(),
        "overflow-block" => "visible".into(),
        "overflow-clip-margin" => "0px".into(),
        "overflow-inline" => "visible".into(),
        "overflow-wrap" => "normal".into(),
        "overflow-x" => "visible".into(),
        "overflow-y" => "visible".into(),
        "overlay" => "none".into(),
        "overscroll-behavior-block" => "auto".into(),
        "overscroll-behavior-inline" => "auto".into(),
        "overscroll-behavior-x" => "auto".into(),
        "overscroll-behavior-y" => "auto".into(),
        "padding-block-end" => "2px".into(),
        "padding-block-start" => "2px".into(),
        "padding-inline-end" => "2px".into(),
        "padding-inline-start" => "2px".into(),
        "paint-order" => "normal".into(),
        "perspective" => "none".into(),
        "perspective-origin" => "103px 43px".into(),
        "position-anchor" => "normal".into(),
        "position-area" => "none".into(),
        "position-try-fallbacks" => "none".into(),
        "position-try-order" => "normal".into(),
        "position-visibility" => "anchors-visible".into(),
        "print-color-adjust" => "economy".into(),
        "quotes" => "auto".into(),
        "r" => "0px".into(),
        "reading-flow" => "normal".into(),
        "reading-order" => "0".into(),
        "resize" => "none".into(),
        "right" => "auto".into(),
        "rotate" => "none".into(),
        "row-gap" => "normal".into(),
        "row-rule-break" => "normal".into(),
        "row-rule-color" => "rgb(51, 51, 51)".into(),
        "row-rule-inset-cap-end" => "0px".into(),
        "row-rule-inset-cap-start" => "0px".into(),
        "row-rule-inset-junction-end" => "0px".into(),
        "row-rule-inset-junction-start" => "0px".into(),
        "row-rule-style" => "none".into(),
        "row-rule-visibility-items" => "normal".into(),
        "row-rule-width" => "3px".into(),
        "ruby-align" => "space-around".into(),
        "ruby-overhang" => "auto".into(),
        "ruby-position" => "over".into(),
        "rule-overlap" => "row-over-column".into(),
        "rx" => "auto".into(),
        "ry" => "auto".into(),
        "scale" => "none".into(),
        "scroll-axis-lock" => "auto".into(),
        "scroll-behavior" => "auto".into(),
        "scroll-initial-target" => "none".into(),
        "scroll-margin-block-end" => "0px".into(),
        "scroll-margin-block-start" => "0px".into(),
        "scroll-margin-bottom" => "0px".into(),
        "scroll-margin-inline-end" => "0px".into(),
        "scroll-margin-inline-start" => "0px".into(),
        "scroll-margin-left" => "0px".into(),
        "scroll-margin-right" => "0px".into(),
        "scroll-margin-top" => "0px".into(),
        "scroll-marker-group" => "none".into(),
        "scroll-padding-block-end" => "auto".into(),
        "scroll-padding-block-start" => "auto".into(),
        "scroll-padding-bottom" => "auto".into(),
        "scroll-padding-inline-end" => "auto".into(),
        "scroll-padding-inline-start" => "auto".into(),
        "scroll-padding-left" => "auto".into(),
        "scroll-padding-right" => "auto".into(),
        "scroll-padding-top" => "auto".into(),
        "scroll-snap-align" => "none".into(),
        "scroll-snap-stop" => "normal".into(),
        "scroll-snap-type" => "none".into(),
        "scroll-target-group" => "none".into(),
        "scroll-timeline-axis" => "block".into(),
        "scroll-timeline-name" => "none".into(),
        "scrollbar-color" => "auto".into(),
        "scrollbar-gutter" => "auto".into(),
        "scrollbar-width" => "auto".into(),
        "shape-image-threshold" => "0".into(),
        "shape-margin" => "0px".into(),
        "shape-outside" => "none".into(),
        "shape-rendering" => "auto".into(),
        "speak" => "normal".into(),
        "stop-color" => "rgb(0, 0, 0)".into(),
        "stop-opacity" => "1".into(),
        "stroke" => "none".into(),
        "stroke-dasharray" => "none".into(),
        "stroke-dashoffset" => "0px".into(),
        "stroke-linecap" => "butt".into(),
        "stroke-linejoin" => "miter".into(),
        "stroke-miterlimit" => "4".into(),
        "stroke-opacity" => "1".into(),
        "stroke-width" => "1px".into(),
        "tab-size" => "8".into(),
        "table-layout" => "auto".into(),
        "text-align-last" => "auto".into(),
        "text-anchor" => "start".into(),
        "text-autospace" => "no-autospace".into(),
        "text-box-edge" => "auto".into(),
        "text-box-trim" => "none".into(),
        "text-combine-upright" => "none".into(),
        "text-decoration" => "none".into(),
        "text-decoration-color" => "rgb(51, 51, 51)".into(),
        "text-decoration-line" => "none".into(),
        "text-decoration-skip-ink" => "auto".into(),
        "text-decoration-style" => "solid".into(),
        "text-decoration-thickness" => "auto".into(),
        "text-emphasis-color" => "rgb(51, 51, 51)".into(),
        "text-emphasis-position" => "over".into(),
        "text-emphasis-style" => "none".into(),
        "text-fit" => "none".into(),
        "text-justify" => "auto".into(),
        "text-orientation" => "mixed".into(),
        "text-overflow" => "clip".into(),
        "text-size-adjust" => "auto".into(),
        "text-spacing-trim" => "normal".into(),
        "text-underline-offset" => "auto".into(),
        "text-underline-position" => "auto".into(),
        "text-wrap-mode" => "wrap".into(),
        "text-wrap-style" => "auto".into(),
        "timeline-scope" => "none".into(),
        "timeline-trigger-activation-range-end" => "normal".into(),
        "timeline-trigger-activation-range-start" => "normal".into(),
        "timeline-trigger-active-range-end" => "auto".into(),
        "timeline-trigger-active-range-start" => "auto".into(),
        "timeline-trigger-name" => "none".into(),
        "timeline-trigger-source" => "auto".into(),
        "top" => "auto".into(),
        "touch-action" => "auto".into(),
        "transform-box" => "view-box".into(),
        "transform-origin" => "103px 43px".into(),
        "transform-style" => "flat".into(),
        "transition-behavior" => "normal".into(),
        "transition-delay" => "0s".into(),
        "transition-duration" => "0s".into(),
        "transition-property" => "all".into(),
        "transition-timing-function" => "ease".into(),
        "translate" => "none".into(),
        "trigger-scope" => "none".into(),
        "unicode-bidi" => "isolate".into(),
        "user-select" => "auto".into(),
        "vector-effect" => "none".into(),
        "view-timeline-axis" => "block".into(),
        "view-timeline-inset" => "auto".into(),
        "view-timeline-name" => "none".into(),
        "view-transition-class" => "none".into(),
        "view-transition-group" => "normal".into(),
        "view-transition-name" => "none".into(),
        "view-transition-scope" => "none".into(),
        "white-space-collapse" => "collapse".into(),
        "widows" => "2".into(),
        "will-change" => "auto".into(),
        "window-drag" => "none".into(),
        "writing-mode" => "horizontal-tb".into(),
        "x" => "0px".into(),
        "y" => "0px".into(),
        "zoom" => "1".into(),
        _ => "".into(),
    }
}

deno_core::extension!(
    layout_extension,
    ops = [
        op_layout_get_bounding_rect,
        op_layout_get_offset_width,
        op_layout_get_offset_height,
        op_layout_get_offset_top,
        op_layout_get_offset_left,
        op_get_computed_style,
    ],
);
